name: test

on:
  push:
    branches:
      - stg

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: echo test
        run: |
          echo triggered!!!
