name: dispatch

defaults:
  run:
    working-directory: ./

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        required: true
        description: 環境
        options:
          - dev
          - stg
          - preprod
          - prod
      companyId:
        type: string
        required: true
        description: 加盟店ID
      domain:
        type: string
        required: true
        description: 加盟店のドメイン
      method:
        type: choice
        required: true
        description: ACMの検証方法
        options:
          - EMAIL
          - DNS

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Define Environment
        run: echo "ENV_NAME=$(echo '${{ (github.event.inputs.target == 'preprod' && 'prod') || github.event.inputs.target }}')" >> $GITHUB_ENV

      - name: echo is prod
        run: echo ${{ (contains(github.event.inputs.target, 'prod') && 'prodある') || 'prodではない' }}

      - name: test shell
        run: |
          yes | bash test.sh
#       - name: Define AWS Assume Role ARN
#         id: define_assume_role_arn
#         run: echo ::set-output name=AWS_ASSUME_ROLE_ARN::$(echo '${{ toJSON(secrets) }}' | jq -r ".AWS_ASSUME_ROLE_ARN_${ENV_NAME^^}")
#       - name: confirm role_arn
#         run: echo "${{ steps.define_assume_role_arn.outputs.AWS_ASSUME_ROLE_ARN }}"

#       - name: run script
#         run: |
#           bash test.sh "${{ github.event.inputs.companyId }}" "${{ github.event.inputs.role }}"
