name: dispatch

defaults:
  run:
    working-directory: ./

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        required: true
        description: 環境
        options:
          - stg
          - prod
      companyId:
        type: string
        required: true
        description: 加盟店ID
      email:
        type: string
        required: true
        description: メール
        default: 'email@example.com'
      name:
        type: string
        required: true
        description: アカウント名
      role:
        type: choice
        required: true
        description: アカウントの権限
        options:
          - ADMIN
          - OPE
          - VIEW

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: inputs confirm
        run: |
          echo target: "${{ github.event.inputs.target }}"
          echo companyId: "${{ github.event.inputs.companyId }}"
          echo email: "${{ github.event.inputs.email }}"
          echo name: "${{ github.event.inputs.name }}"
          echo role: "${{ github.event.inputs.role }}"
      - name: Define Environment
        run: echo "ENV_NAME=$(echo '${{ github.event.inputs.target }}')" >> $GITHUB_ENV

      - name: Define AWS Assume Role ARN
        id: define_assume_role_arn
        run: echo ::set-output name=AWS_ASSUME_ROLE_ARN::$(echo '${{ toJSON(secrets) }}' | jq -r ".AWS_ASSUME_ROLE_ARN_${ENV_NAME^^}")
      - name: confirm role_arn
        run: echo "${{ steps.define_assume_role_arn.outputs.AWS_ASSUME_ROLE_ARN }}"

      - name: run script
        run: |
          bash test.sh "${{ github.event.inputs.companyId }}" "${{ github.event.inputs.role }}"
